version: "2"
services:
  client:
    build: client
    ports:
      - "4200:4200"
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/.angular-cli.json:/usr/src/app/.angular-cli.json
      - ./client/tslint.json:/usr/src/app/tslint.json
    command: sh -c "node_modules/.bin/ng lint && node_modules/.bin/ng serve --host 0.0.0.0"
